name: Create Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download File
        run: |
          wget -O downloaded_file.txt https://example.com/file.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: downloaded_file.txt
